import json

# --- 1. Translation Map (The "Bridge") ---
# Since we haven't added metadata to nodes yet, we map them here manually 
# so the exported script works immediately.
FUNCTION_MAP = {
    # Filters
    "gaussian_blur": "skimage.filters.gaussian",
    "median_filter": "skimage.filters.median",
    "unsharp_mask": "skimage.filters.unsharp_mask",
    "sobel": "skimage.filters.sobel",
    
    # Morphology
    "binary_closing": "skimage.morphology.closing",
    "binary_opening": "skimage.morphology.opening",
    "dilation": "skimage.morphology.dilation",
    "erosion": "skimage.morphology.erosion",
    "remove_small_objects": "skimage.morphology.remove_small_objects",
    "skeletonize": "skimage.morphology.skeletonize",
    
    # Segmentation
    "threshold_otsu": "skimage.filters.threshold_otsu",
    "threshold_local": "skimage.filters.threshold_local",
    "label_objects": "skimage.measure.label",
    "clear_border": "skimage.segmentation.clear_border",
    
    # Transform
    "rotate_image": "skimage.transform.rotate",
    "rescale_image": "skimage.transform.rescale",
    
    # Math
    "gamma_correction": "skimage.exposure.adjust_gamma",
    "invert_image": "skimage.util.invert"
}

class ScriptGenerator:
    def __init__(self, scene):
        self.scene = scene

    def generate(self):
        """Generates a Python script string from the current graph."""
        from .napari_plugin_v2 import Node, NODE_LIBRARY
        
        # 1. Get and Sort Nodes
        nodes = [item for item in self.scene.items() if isinstance(item, Node)]
        if not nodes:
            return "# Empty Pipeline"

        sorted_nodes = self.topological_sort(nodes)
        
        # 2. Setup Script Header
        script = []
        script.append("# Auto-generated by Napari Flow Editor")
        script.append("import numpy as np")
        script.append("import skimage")
        script.append("import skimage.io")
        script.append("import skimage.filters")
        script.append("import skimage.morphology")
        script.append("import skimage.segmentation")
        script.append("import skimage.transform")
        script.append("import skimage.util")
        script.append("import skimage.measure")
        script.append("import skimage.exposure")
        script.append("")
        script.append("# --- PIPELINE START ---")
        script.append("")

        # Dictionary to map Node UID -> Variable Name
        node_vars = {}
        name_counts = {}

        for node in sorted_nodes:
            # A. Generate Variable Name (e.g., gaussian_blur_1)
            base_name = node.title.lower().replace(" ", "_").replace("(", "").replace(")", "")
            count = name_counts.get(base_name, 0) + 1
            name_counts[base_name] = count
            var_name = f"{base_name}_{count}"
            node_vars[node.uid] = var_name

            # B. Handle INPUT Node
            if node.node_type == "get_layer":
                layer_name = node.parameters.get("layer_name", "Unknown")
                script.append(f"# Load Input: '{layer_name}'")
                # We put a placeholder filename because we can't know the real file path from a Napari layer
                script.append(f"{var_name} = skimage.io.imread('replace_with_path_to_{layer_name}.tif')")
                script.append("")
                continue

            # C. Handle Processing Nodes
            if node.node_type not in NODE_LIBRARY:
                script.append(f"# Error: Unknown node type {node.node_type}")
                continue

            def_data = NODE_LIBRARY[node.node_type]
            
            # --- ARGUMENT MAPPING ---
            args_str = []
            
            # 1. Map Inputs (Connections)
            for socket in node.inputs:
                if socket.connected_edges:
                    edge = socket.connected_edges[0]
                    source_node = edge.start_socket.node
                    if source_node.uid in node_vars:
                        src_var = node_vars[source_node.uid]
                        
                        # HACK: Most skimage functions allow the image as the first positional argument.
                        # To be safe, we usually just pass it as the first arg without name, 
                        # OR we map 'image_in' -> 'image'.
                        # Let's try passing as positional argument first for the image.
                        if socket.name in ["image", "image_in", "layer_data"]:
                             args_str.insert(0, src_var) # Positional arg 0
                        else:
                             args_str.append(f"{socket.name}={src_var}")

            # 2. Map Parameters
            for param, val in node.parameters.items():
                # Handle strings vs numbers
                if isinstance(val, str):
                    args_str.append(f"{param}='{val}'")
                else:
                    args_str.append(f"{param}={val}")

            # --- FUNCTION RESOLUTION ---
            # Use our Dictionary map, or fall back to the wrapper name
            internal_name = def_data["execution_path"].split(".")[-1]
            func_call = FUNCTION_MAP.get(internal_name, f"custom_module.{internal_name}")

            # D. Construct Line
            script.append(f"# Step: {node.title}")
            script.append(f"{var_name} = {func_call}({', '.join(args_str)})")
            script.append("")

        return "\n".join(script)

    def topological_sort(self, nodes):
        visited = set()
        stack = []
        def visit(n):
            if n in visited: return
            visited.add(n)
            for input_socket in n.inputs:
                if input_socket.connected_edges:
                    visit(input_socket.connected_edges[0].start_socket.node)
            stack.append(n)
        for node in nodes: visit(node)
        return stack
